version: '2'
services:
  npm:
    image: node:15.4.0-alpine3.12
    working_dir: "/app"
    user: node
    volumes:
     - ".:/app"
    entrypoint: ["npm"]
  storybook:
    image: node:15.4.0-alpine3.12
    working_dir: "/app"
    user: node
    ports:
      - 9090:9090
    volumes:
      - ".:/app"
    entrypoint: ["npm", "run", "storybook"]
